version: 2
updates:
  # Swift Package Manager dependencies
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
